<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="Microsoft.Azure.Cosmos" />
      <PackageReference Include="Microsoft.Extensions.Options" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\IK.Imager.Storage.Abstractions\IK.Imager.Storage.Abstractions.csproj" />
      <ProjectReference Include="..\IK.Imager.Utils\IK.Imager.Utils.csproj" />
    </ItemGroup>

</Project>
