<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Storage.Blobs" Version="12.29.1" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\IK.Imager.Storage.Abstractions\IK.Imager.Storage.Abstractions.csproj" />
      <ProjectReference Include="..\IK.Imager.Utils\IK.Imager.Utils.csproj" />
    </ItemGroup>

</Project>
