#docker-compose -f docker-compose.yml -f docker-compose.override.yml up

version: '3.4'

services:
  ik.imager.api:
    image: ilyakhorev/ik-imager-api:1.0
#    build:
#      context: .
#      dockerfile: IK.Imager.Api\Dockerfile
    environment:
      - ServiceBus__ConnectionString=${ServiceBus_ConnectionString}
      - AzureStorage__ConnectionString=${AzureStorage_ConnectionString}
      - CosmosDb__ConnectionString=${CosmosDb_ConnectionString}
      - Logging__LogLevel__Default=${LogLevel_Default}
      - Logging__ApplicationInsights__LogLevel__Default=${LogLevel_Default}
      - APPINSIGHTS_INSTRUMENTATIONKEY=${AppInsights_InstrumentationKey}
      - ApplicationInsights__AuthenticationApiKey=${AppInsights_AuthenticationApiKey}